[2025-03-24T10:19:29.628+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_filtered_data_and_upload_to_gcs.fetch_and_upload_filtered_data manual__2025-03-24T10:19:27.166778+00:00 [queued]>
[2025-03-24T10:19:29.639+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_filtered_data_and_upload_to_gcs.fetch_and_upload_filtered_data manual__2025-03-24T10:19:27.166778+00:00 [queued]>
[2025-03-24T10:19:29.639+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-03-24T10:19:29.653+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): fetch_and_upload_filtered_data> on 2025-03-24 10:19:27.166778+00:00
[2025-03-24T10:19:29.657+0000] {standard_task_runner.py:60} INFO - Started process 2452 to run task
[2025-03-24T10:19:29.660+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_filtered_data_and_upload_to_gcs', 'fetch_and_upload_filtered_data', 'manual__2025-03-24T10:19:27.166778+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/step_one.py', '--cfg-path', '/tmp/tmpehue6tzq']
[2025-03-24T10:19:29.661+0000] {standard_task_runner.py:88} INFO - Job 131: Subtask fetch_and_upload_filtered_data
[2025-03-24T10:19:29.705+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_filtered_data_and_upload_to_gcs.fetch_and_upload_filtered_data manual__2025-03-24T10:19:27.166778+00:00 [running]> on host 3d764bfd33f3
[2025-03-24T10:19:29.784+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_filtered_data_and_upload_to_gcs' AIRFLOW_CTX_TASK_ID='fetch_and_upload_filtered_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T10:19:27.166778+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T10:19:27.166778+00:00'
[2025-03-24T10:20:06.506+0000] {logging_mixin.py:188} INFO - Successfully fetched https://cycling.data.tfl.gov.uk/ActiveTravelCountsProgramme/2023%20W1%20spring-Central.csv
[2025-03-24T10:20:28.753+0000] {logging_mixin.py:188} INFO - Successfully fetched https://cycling.data.tfl.gov.uk/ActiveTravelCountsProgramme/2024%20W1%20spring-Central.csv
[2025-03-24T10:20:29.620+0000] {logging_mixin.py:188} INFO - Successfully fetched https://cycling.data.tfl.gov.uk/ActiveTravelCountsProgramme/1%20Monitoring%20locations.csv
[2025-03-24T10:20:29.639+0000] {logging_mixin.py:188} INFO - Error processing data from https://cycling.data.tfl.gov.uk/ActiveTravelCountsProgramme/1%20Monitoring%20locations.csv: 'Mode'
[2025-03-24T10:20:29.691+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/step_one.py", line 94, in fetch_filtered_data_and_upload_to_gcs
    upload_to_gcs(filtered_data)
  File "/opt/airflow/dags/step_one.py", line 71, in upload_to_gcs
    gcs_hook = GCSHook(gcp_conn_id='my_gcp_connection')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 159, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 251, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 514, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `my_gcp_connection` isn't defined
[2025-03-24T10:20:29.699+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=fetch_filtered_data_and_upload_to_gcs, task_id=fetch_and_upload_filtered_data, execution_date=20250324T101927, start_date=20250324T101929, end_date=20250324T102029
[2025-03-24T10:20:29.714+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 131 for task fetch_and_upload_filtered_data (The conn_id `my_gcp_connection` isn't defined; 2452)
[2025-03-24T10:20:29.748+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-24T10:20:29.766+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
