[2025-03-24T09:30:13.093+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: test_fetch_url_csv.fetch_and_log_csv_urls manual__2025-03-24T09:30:43.940279+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
