[2025-03-24T08:39:42.872+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_filtered_data_and_upload_to_gcs.download_and_upload_filtered_files manual__2025-03-24T08:35:04.072704+00:00 [queued]>
[2025-03-24T08:39:42.886+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_filtered_data_and_upload_to_gcs.download_and_upload_filtered_files manual__2025-03-24T08:35:04.072704+00:00 [queued]>
[2025-03-24T08:39:42.887+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2025-03-24T08:39:42.910+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): download_and_upload_filtered_files> on 2025-03-24 08:35:04.072704+00:00
[2025-03-24T08:39:42.917+0000] {standard_task_runner.py:60} INFO - Started process 718 to run task
[2025-03-24T08:39:42.923+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_filtered_data_and_upload_to_gcs', 'download_and_upload_filtered_files', 'manual__2025-03-24T08:35:04.072704+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/step_one.py', '--cfg-path', '/tmp/tmpfsbzrsk7']
[2025-03-24T08:39:42.927+0000] {standard_task_runner.py:88} INFO - Job 105: Subtask download_and_upload_filtered_files
[2025-03-24T08:39:43.007+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_filtered_data_and_upload_to_gcs.download_and_upload_filtered_files manual__2025-03-24T08:35:04.072704+00:00 [running]> on host 3d764bfd33f3
[2025-03-24T08:39:43.155+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_filtered_data_and_upload_to_gcs' AIRFLOW_CTX_TASK_ID='download_and_upload_filtered_files' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T08:35:04.072704+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-24T08:35:04.072704+00:00'
[2025-03-24T08:39:44.440+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 439, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/step_one.py", line 45, in download_and_upload_multiple_files
    csv_urls = get_csv_urls_from_website(base_url, subdirectory_url)
  File "/opt/airflow/dags/step_one.py", line 25, in get_csv_urls_from_website
    raise Exception(f"Failed to fetch the website. Status code: {response.status_code}")
Exception: Failed to fetch the website. Status code: 404
[2025-03-24T08:39:44.451+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_filtered_data_and_upload_to_gcs, task_id=download_and_upload_filtered_files, execution_date=20250324T083504, start_date=20250324T083942, end_date=20250324T083944
[2025-03-24T08:39:44.472+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 105 for task download_and_upload_filtered_files (Failed to fetch the website. Status code: 404; 718)
[2025-03-24T08:39:44.513+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-03-24T08:39:44.540+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
